app:
  action-log:
    enabled: false
spring:
  datasource:
    hikari:
      maximum-pool-size: 5
  h2:
    console:
      enabled: false
  jpa:
    hibernate:
      ddl-auto: validate
  main:
    banner-mode: log
  mvc:
    hiddenmethod:
      filter:
        enabled: true
  session:
    timeout: 15m
