spring:
  datasource:
    hikari:
      maximum-pool-size: 5
  jpa:
    hibernate:
      ddl-auto: validate
  main:
    banner-mode: log
  mvc:
    hiddenmethod:
      filter:
        enabled: true
  session:
    timeout: 15m
