spring:
  datasource:
    url: jdbc:h2:mem:vaccination;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password: 
  jpa:
    hibernate:
      ddl-auto: validate
  mvc:
    hiddenmethod:
      filter:
        enabled: true
