# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on: workflow_dispatch

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11
    - name: Cache local Maven repository
      uses: actions/cache@v2
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-
    - name: Build with Maven(VACCINATION-SCHEDULER-ADMIN)
      working-directory: $GITHUB_WORKSPACE/vaccination-scheduler-admin
      run: ./mvnw -B clean test --file pom.xml
    - name: Build with Maven(VACCINATION-SCHEDULER-PUBLIC)
      working-directory: $GITHUB_WORKSPACE/vaccination-scheduler-public
      run: ./mvnw -B clean test --file pom.xml
